### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by hillarygreenlerman** [buschbirk/intro-data-capstone-musclehub#14]
Overall, this was a beautifully done project; great job!

For the Chi-Squared tests, you consistently used the wrong contingency table.  Remember that each column needs to be a separate condition (i.e., Made a Purchase vs. Did Not Make a Purchase).  "Total" should not appear in your contingency table.

The Matplotlib visualizations were gorgeous.  You went above-and-beyond by learning about style sheets and adding labels to your bar charts.  Each visualization communicated your points very well.

Your suggestions for further research were also really interesting.  I hope that you get a chance to play around with this dataset (or another) and do more research.

**Comment by buschbirk** [comment]
Thanks a lot. That was a very thorough and helpful review! 
It's a shame that I made that mistake on the contingency tables, but at least it was consistent :D
And now I'll be aware of it for future use.

Thanks for an awesome course!
