### ISSUE TITLE
Make your life easier with aliases

### ISSUE THREAD

**Issue by hillarygreenlerman** [buschbirk/intro-data-capstone-musclehub#3]
https://github.com/buschbirk/intro-data-capstone-musclehub/blob/66253a292dbe1c2e164ec5b57ff40c1a6da26ecf/Final%20Analysis/musclehub.py#L127

Typing out `fitness_test` multiple times is a pain.  You can make your life easier by aliasing each table with something shorter, like `ft`.

Here's an example:
```sql
SELECT v.first_name,
    ft.fitness_test_date,
    p.purchase_date
FROM visits v
LEFT JOIN fitness_tests ft
    ON ft.first_name = v.last_name
    AND ft.last_name = v.last_name
...
```

**Comment by buschbirk** [comment]
Didn't know you could alias the whole table! Cool :)
