### ISSUE TITLE
Add spaces around operations for increased readability

### ISSUE THREAD

**Issue by hillarygreenlerman** [buschbirk/intro-data-capstone-musclehub#8]
https://github.com/buschbirk/intro-data-capstone-musclehub/blob/66253a292dbe1c2e164ec5b57ff40c1a6da26ecf/Final%20Analysis/musclehub.py#L253

This one is super nitpicky:

Generally, we put spaces around operations like `*` or `/` to increase readability:

```py
app_pivot['Percent with Application'] = 100 * app_pivot['Application'] / app_pivot['No Application']
```

**Comment by buschbirk** [comment]
That is definitely easier on the eyes. :)
