### ISSUE TITLE
Incorrect contingency table

### ISSUE THREAD

**Issue by hillarygreenlerman** [buschbirk/intro-data-capstone-musclehub#9]
https://github.com/buschbirk/intro-data-capstone-musclehub/blob/66253a292dbe1c2e164ec5b57ff40c1a6da26ecf/Final%20Analysis/musclehub.py#L280-L284

This one is tricky!

Your contingency table should be like this:

|Group | Not Applicants | Applicants |
|-|-|-|
| A| ? | ? |
|B| ?| ?|

Each column of your contingency table is meant to represent a different outcome, not the total of all outcomes.

In this case, your p-value is quite close to the correct value because "Not Applicants" is quite close to the "Total".

**Comment by buschbirk** [comment]
Damn, that was a big one. It's been corrected.
